-- Resposta Exercício 4: união com Intersecção
(SELECT NUMERO_CONTA 
 FROM EXTRATO
 WHERE NOME_TITULAR = 'Rory Fry'
 OR NOME_TITULAR = 'Amari Black')

INTERSECT

SELECT E.NUMERO_CONTA
FROM EXTRATO E
JOIN REGISTRO R ON E.ID = R.ID_EXTRATO
WHERE R.VALOR > 300;