-- Resposta Exercício 5: intersecção com Diferença
(SELECT NUMERO_CONTA 
 FROM EXTRATO
 WHERE NOME_TITULAR = 'Kameron York'
 OR NOME_TITULAR = 'Ryland Kelly')

EXCEPT

SELECT E.NUMERO_CONTA
FROM EXTRATO E
JOIN REGISTRO R ON E.ID = R.ID_EXTRATO
WHERE R.VALOR BETWEEN 100 AND 500;