-- Resposta Exercício 6: diferença de Conjuntos com União
(SELECT NUMERO_CONTA 
 FROM EXTRATO
 WHERE NOME_TITULAR = 'Rory Fry'

 EXCEPT

 SELECT E.NUMERO_CONTA
 FROM EXTRATO E
 JOIN REGISTRO R ON E.ID = R.ID_EXTRATO
 WHERE R.VALOR < 1000)

UNION

SELECT NUMERO_CONTA
FROM EXTRATO
WHERE NOME_TITULAR = 'Amari Black';