-- Resposta Exercício 7: intersecção em Subconsulta
SELECT NUMERO_CONTA 
FROM EXTRATO
WHERE NOME_TITULAR = 'Kameron York'

INTERSECT

SELECT E.NUMERO_CONTA
FROM EXTRATO E
JOIN REGISTRO R ON E.ID = R.ID_EXTRATO
WHERE R.VALOR BETWEEN 500 AND 1000;