-- Resposta Exercício 8: uso de Parênteses com UNION e INTERSECT
(SELECT NUMERO_CONTA
 FROM EXTRATO
 WHERE NOME_TITULAR = 'Kameron York'

 INTERSECT

 SELECT E.NUMERO_CONTA
 FROM EXTRATO E
 JOIN REGISTRO R ON E.ID = R.ID_EXTRATO
 WHERE R.VALOR > 300)

UNION

SELECT NUMERO_CONTA
FROM EXTRATO
WHERE NOME_TITULAR = 'Daisy Marquez';
