-- Resposta Exercício 5: consultas Aninhadas com EXCEPT**
(SELECT E.NUMERO_CONTA
 FROM EXTRATO E
 JOIN REGISTRO R ON E.ID = R.ID_EXTRATO
 WHERE R.VALOR > 500)

EXCEPT

SELECT E.NUMERO_CONTA
FROM EXTRATO E
JOIN REGISTRO R ON E.ID = R.ID_EXTRATO
WHERE R.VALOR < 100;
