-- Resposta Exercício 10: operações Múltiplas (UNION, INTERSECT, EXCEPT)
(SELECT NUMERO_CONTA
 FROM EXTRATO
 WHERE NOME_TITULAR = 'Ryland Kelly'

 UNION

 SELECT E.NUMERO_CONTA
 FROM EXTRATO E
 JOIN REGISTRO R ON E.ID = R.ID_EXTRATO
 WHERE R.VALOR > 700)

INTERSECT

SELECT E.NUMERO_CONTA
FROM EXTRATO E
JOIN REGISTRO R ON E.ID = R.ID_EXTRATO
JOIN TIPO_REGISTRO T ON R.ID_TIPO = T.ID
WHERE T.TIPO = 'SAIDA'

EXCEPT

SELECT E.NUMERO_CONTA
FROM EXTRATO E
JOIN REGISTRO R ON E.ID = R.ID_EXTRATO
WHERE R.VALOR < 200;
